name: first push
on:
  push: 
  workflow_dispatch:

jobs:
  Tarea1:
    runs-on: ubuntu-latest

    steps:
      - name: Desplegar datos del push
        run: |
          echo "Mensaje del commit: ${{ github.event.head_commit.message }}"
          echo "Autor: ${{ github.event.head_commit.author.name }} (<${{ github.event.head_commit.author.email }}>)"
          echo "ID del commit: ${{ github.sha }}"
          echo "URL del commit: ${{ github.event.head_commit.url }}"
          echo "My ID 1222100504"
          echo "Rama: ${{ github.ref_name }}"
          echo "Repositorio: ${{ github.repository }}"
          echo "Fecha de ejecución:"
          date
